apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wbct
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbct
    app.kubernetes.io/part-of: byoc-app-hwbd
  name: wbct8stu
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: wbct
    weight: null
status: {}
